api_version = "2025-04"

[[extensions]]
name = "t:name"
handle = "price-change"
type = "function"
description = "t:description"

  [[extensions.targeting]]
  target = "purchase.cart-transform.run"
  input_query = "src/cartTransformRun.graphql"
  export = "cart-transform-run"

  [extensions.build]
  path = "dist/main.js"
